import ReduxProvider from "@/provider/redux-provider";
import { SessionProvider } from "@/provider/session-provider";
import { ThemeProvider } from "@/provider/theme-provider";
import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "../styles/globals.css";

export const metadata: Metadata = {
    title: "Onno Mart - Ecommerce Website",
    description: "Generated by create next app",
};

const jost = Jost({ subsets: ["latin"] });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${jost.className} antialiased`}
                suppressHydrationWarning
            >
                <SessionProvider>
                    <ReduxProvider>
                        <ThemeProvider
                            attribute="class"
                            defaultTheme="light"
                            enableSystem
                            disableTransitionOnChange
                        >
                            {children}
                        </ThemeProvider>
                    </ReduxProvider>
                </SessionProvider>
            </body>
        </html>
    );
}
